name: fun_unlimited
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  camera: ^0.10.3+1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.3.1
  country_codes: ^2.2.0
  cupertino_icons: ^1.0.2
  easy_image_viewer: ^1.2.0
  extended_nested_scroll_view: ^6.0.0
  file_picker: ^5.2.5
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_pagination: ^3.0.0
  firebase_storage: ^11.0.14
  flutter:
    sdk: flutter
  flutter_countdown_timer: ^4.1.0
  flutter_html: ^2.2.1
  flutter_launcher_icons: ^0.11.0
  flutter_localization: ^0.1.9
  flutter_markdown: ^0.6.13+1
  flutter_vector_icons: ^2.0.0
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.4.0
  geolocator: ^9.0.2
  get: ^4.6.5
  google_fonts: ^4.0.3
  google_sign_in: ^5.4.2
  http: ^0.13.5
  images_picker: ^1.2.11
  intl: ^0.17.0
  linear_step_indicator: ^1.0.0+3
  lottie: ^2.2.0
  permission_handler: ^10.2.0
  provider: ^6.0.5
  pull_to_refresh: ^2.0.0
  quickalert: ^1.0.1
  razorpay_flutter: ^1.3.4
  shared_preferences: ^2.0.17
  video_player: ^2.4.10
  video_thumbnail: ^0.5.3
  visibility_detector: ^0.3.3
  zego_express_engine:
  # zego_uikit_prebuilt_live_audio_room: ^2.4.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/pok.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/games/
    - assets/lafa/
